# Generated by Django 3.2.13 on 2022-10-13 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20221013_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='content',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
